# Site settings
title: Arangear
description: Game programming
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://arangear.github.io"

# User settings
username: Daniel Cieslowski
user_description: Hi, my name is <strong>Daniel</strong> and I'm a programmer specializing in game development.
user_title: C++ Programmer
email: cieslowskids@gmail.com
twitter_username: Arangear
github_username: Arangear

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
